{
 "title": "Kafka Metrics",
 "tags": [
  "consumer",
  "producer",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer Events Sent (Success)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "producer_events_sent_total{status=\"success\"}",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Producer Events Sent (Failure)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "producer_events_sent_total{status=\"failure\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Consumer Events Processed (Success)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "events_received_total{status=\"success\"}"
    }
   ]
  },
  {
   "title": "Consumer Events Processed (Failure)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "events_received_total{status=\"failure\"}"
    }
   ]
  },
  {
   "title": "Consumer Events Processing Time (Histogram Average)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(event_processing_seconds_sum[1m]) / rate(event_processing_seconds_count[1m])"
    }
   ]
  }
 ]
}